// Pure markdown-section helpers for the knowledgebase. No I/O, no next/*.
// The KB is one markdown string; "## " headings delimit sections. The
// founder-authored recovery section is merged/preserved with these, never
// generated by the model (see ai/prompts/kb.ts).

export const RECOVERY_SECTION = "When Something Goes Wrong";

// Insertion anchor for new sections: the KB's catch-all final section.
const ANCHOR_SECTION = "Facts a reply might reference";

type Section = { title: string | null; body: string };

/** Split markdown into a preamble (title: null) plus one entry per "## " heading. */
function splitSections(kbMd: string): Section[] {
  const sections: Section[] = [];
  let current: Section = { title: null, body: "" };
  for (const line of kbMd.split("\n")) {
    const m = line.match(/^##\s+(.+?)\s*$/);
    if (m) {
      sections.push(current);
      current = { title: m[1], body: "" };
    } else {
      current.body += (current.body ? "\n" : "") + line;
    }
  }
  sections.push(current);
  return sections;
}

function render(sections: Section[]): string {
  return sections
    .filter((s) => s.title !== null || s.body.trim() !== "")
    .map((s) => {
      if (s.title === null) return s.body.trim();
      const body = s.body.trim();
      return body ? `## ${s.title}\n${body}` : `## ${s.title}`;
    })
    .join("\n\n");
}

/** Return a section's body (without its heading), or null if absent. */
export function extractKbSection(kbMd: string, sectionTitle: string): string | null {
  const hit = splitSections(kbMd).find((s) => s.title === sectionTitle);
  return hit ? hit.body.trim() : null;
}

/**
 * Replace the named section, or insert it before the "Facts a reply might
 * reference" anchor (append at end if the anchor is missing). Idempotent.
 */
export function upsertKbSection(
  kbMd: string,
  sectionTitle: string,
  body: string,
): string {
  const sections = splitSections(kbMd);
  const updated: Section = { title: sectionTitle, body: body.trim() };
  const i = sections.findIndex((s) => s.title === sectionTitle);
  if (i >= 0) {
    sections[i] = updated;
  } else {
    const anchor = sections.findIndex((s) => s.title === ANCHOR_SECTION);
    if (anchor >= 0) sections.splice(anchor, 0, updated);
    else sections.push(updated);
  }
  return render(sections);
}
